on:
    workflow_run:
        workflows: ['Repro issue test']
        types:
            - completed

name: Repro issue report
jobs:
    report:
        name: Report repro issue to GitHub
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: npm install
              run: npm ci

            - uses: actions/download-artifact@v2
              with:
                  name: repro-issue-report

            - name: Report to issue
              run: |
                  node ./packages/repro-issue/src/report.js
